version: '3.9'

networks:
  my_network: {}

volumes:
  postgres_data: {}

services:
  app:
    restart: always
    image: azamatkomaev/postcreator:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/mydb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db
    networks:
      - my_network
  db:
    restart: always
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
