spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.sql
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
